# Configuration options are documented at:
# http://about.travis-ci.org/docs/user/languages/ruby/
language: ruby
bundler_args: --without development
rvm:
  - 1.8.7
  - 2.0.0
gemfile:
  - Gemfile
branches:
  only:
    - master
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
